# Generated by Django 3.2.9 on 2021-12-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211204_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_fire_user', 'Pode Demitir Usuarios'), ('can_create_project', 'Pode Criar Novos Projetos')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
