# Generated by Django 3.2.9 on 2021-12-04 10:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Project Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Project Description')),
                ('initial_budget', models.DecimalField(decimal_places=2, help_text='The value that had planed to start the project', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Initial Budget')),
                ('start_date', models.DateField(blank=True, help_text='Date that the project will start or already started', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date that the project will end or already ended', verbose_name='End Date')),
                ('is_ended', models.BooleanField(default=False, help_text='To determinate if this project had already ended.', verbose_name='finished')),
                ('is_started', models.BooleanField(default=True, help_text='To determinate if this project had already started.', verbose_name='started')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_update_project', 'Pode atualizar o Projeto'),),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(help_text='Users that are related with this project', related_name='projects', through='projects.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
