# Generated by Django 3.2.9 on 2021-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
